### PR TITLE
Update xdebug.ini to use new option names

### PR DESCRIPTION
**Pull request by dshoreman**
## Background

While setting up phpsu/ShellCommandBuilder earlier using docker to get php8, I got a few errors from Xdebug about changed config options. This PR is an attempt to solve them and hopefully provide some background to the changes that's otherwise difficult to find. Hope it helps!

```
Creating shellcommandbuilder_php8_run ... done
Xdebug: [Config] The setting 'xdebug.profiler_enable' has been renamed, see the upgrading guide at https://xdebug.org/docs/upgrade_guide#changed-xdebug.profiler_enable (See: https://xdebug.org/docs/errors#CFG-C-CHANGED)
Xdebug: [Config] The setting 'xdebug.profiler_enable_trigger' has been renamed, see the upgrading guide at https://xdebug.org/docs/upgrade_guide#changed-xdebug.profiler_enable_trigger (See: https://xdebug.org/docs/errors#CFG-C-CHANGED)
Xdebug: [Config] The setting 'xdebug.profiler_output_dir' has been renamed, see the upgrading guide at https://xdebug.org/docs/upgrade_guide#changed-xdebug.profiler_output_dir (See: https://xdebug.org/docs/errors#CFG-C-CHANGED)
Xdebug: [Config] The setting 'xdebug.remote_autostart' has been renamed, see the upgrading guide at https://xdebug.org/docs/upgrade_guide#changed-xdebug.remote_autostart (See: https://xdebug.org/docs/errors#CFG-C-CHANGED)
Xdebug: [Config] The setting 'xdebug.remote_enable' has been renamed, see the upgrading guide at https://xdebug.org/docs/upgrade_guide#changed-xdebug.remote_enable (See: https://xdebug.org/docs/errors#CFG-C-CHANGED)
Xdebug: [Config] The setting 'xdebug.remote_mode' has been renamed, see the upgrading guide at https://xdebug.org/docs/upgrade_guide#changed-xdebug.remote_mode (See: https://xdebug.org/docs/errors#CFG-C-CHANGED)
Xdebug: [Config] The setting 'xdebug.remote_port' has been renamed, see the upgrading guide at https://xdebug.org/docs/upgrade_guide#changed-xdebug.remote_port (See: https://xdebug.org/docs/errors#CFG-C-CHANGED)
```

## Disclaimer

You'll probably want to **test this locally before merging**, just in case. The upgrade guide for xdebug 3.x is seemingly still on the todo list, and the repo's Issues tab has helpfully been disabled so the context for many commits has been replaced with 404s.

From what I can tell, the changes in this PR *should* map correctly to the new names/functionality. That said, some old names are still referenced in places despite the respective `STD_PHP_INI_*` line being removed from `/xdebug.c` so it's unclear exactly what the changes affect (if anything).

Along the way I made a note of any relevant commits I found; those are linked below for reference.

### `remote_{host,port}`
Changed to `client_host` and `client_port` in [f5478a][1]. This one's a simple rename.

### `profiler_enable[_trigger]` and `remote_{autostart,mode,enable}`
These were all [removed][2] in [59b32a][3], with a combination of `mode` and `start_with_request` taking their place.

The `mode` option takes a comma-separated [list of values][4], with the `profile` mode replacing the old `profiler_enable` option.

Setting `start_with_request=default` will enable autostart automatically [when in either debug or profile mode][5], also removing the need for `remote_autostart`, `remote_mode` and `profiler_enable_trigger`.

### `remote_connect_back`
Changed to `discover_client_host` in [a97e70][6]--another simple rename.

### `profiler_output_dir`
Merged into the existing `output_dir` option (along with `trace_output_dir` and `gc_stats_output_dir`) in [9bb017][7].

---

[List of (most?) changed settings](https://github.com/xdebug/xdebug/commit/a349893d09b44267ec44bbe78c0a4bbe68dd6491#diff-50b7f832915ee1d6491a14aa16a90786R291)

[1]: https://github.com/xdebug/xdebug/commit/f5478ad2680823c7fd33bf543b65d43899144b02
[2]: https://github.com/xdebug/xdebug/commit/b93120d829737145b3d33cf73d9054df2309a907
[3]: https://github.com/xdebug/xdebug/commit/59b32a93782a346d86aac48b7163c73b0a17b51e#diff-50b7f832915ee1d6491a14aa16a90786
[4]: https://github.com/xdebug/xdebug/commit/f5fc23f2a529e8cf5eb85d9d2153b51017c30ba7#diff-89af3632fd635465b57b5e0cda91dfefR55-R84
[5]: https://github.com/xdebug/xdebug/commit/67c82ce9f5fc4172900b9be385cfd0ab9864d6c7#diff-89af3632fd635465b57b5e0cda91dfefR149-R157
[6]: https://github.com/xdebug/xdebug/commit/a97e70c7dff80bf101eac8bdf4072d8bfb228ca0
[7]: https://github.com/xdebug/xdebug/commit/9bb017019cff227d102a0e963c61b57acceae959

### CODE REVIEW

**Comment by ChrisB9** [comment]
Thanks alot! This looks great already. I will check this out the next days and merge it once everything works out
One thing I'd like to know: Did you run, while using xdebug 3.0, in any segmentation faults?

**Comment by dshoreman** [comment]
I only got as far as trying to run the tests before getting distracted by the xdebug options, then sleep happened :laughing: 

No apparent segfaults, but there *were* 2 errors (one fatal) when I ran `docker-compose run php8 composer test`.

Here's the output that follows after the xdebug warnings in OP:
```sh
Fatal error: Uncaught Error: Call to private method Xhgui\Profiler\Profiler::registerShutdownHandler() from global scope
 in /opt/php-libs/files/profiler.php on line 80

Error: Call to private method Xhgui\Profiler\Profiler::registerShutdownHandler() from global scope in
 /opt/php-libs/files/profiler.php on line 80

Call Stack:
    0.0010     353496   1. {main}() /opt/php-libs/files/profiler.php:0
```

ShellCommandBuilder looks like it could be useful for one of my projects, so I plan to try digging into the PHP 8 support at some point in the next few days. When I find the time to do that, I'll post back if I find anything else along the way.

Will phpsu/ShellCommandBuilder be opted in to Hacktoberfest? Some changes were made a couple days ago so it now requires a `hacktoberfest` tag on the actual repository itself, not just issues: https://hacktoberfest.digitalocean.com/hacktoberfest-update

**Comment by ChrisB9** [comment]
The error you see above happens here: https://github.com/ChrisB9/php8-xdebug/blob/main/php/profiler.php
I never fully finalized the profiler-integration with xhgui because the way data is aggregated has changed dramatically and I didn't have the time yet to explore the new way.

I am very happy to hear, that the ShellCommandBuilder can be of help. May I ask out of curiosity, what kind of project you are going to build with it?

I enabled both repos with the new hacktoberfest label, your PR here should definitely be counted

**Comment by dshoreman** [comment]
> The error you see above happens here: [https://github.com/ChrisB9/php8-xdebug/blob/main/php/profiler.php](https://github.com/ChrisB9/php8-xdebug/blob/main/php/profiler.php?rgh-link-date=2020-10-06T09%3A31%3A17Z)
>
> I never fully finalized the profiler-integration with xhgui because the way data is aggregated has changed dramatically and I didn't have the time yet to explore the new way.

Thanks for this, while trying to find where `Xhgui\Profiler` was installed from (seems I [skipped over it](https://github.com/ChrisB9/php8-xdebug/blob/main/php-dev-8.dockerfile#L155) 3(!) times) I saw some more places that might need config changes. I'll do some digging in perftools/php-profiler to see what I can find--it might be doing its own config parsing which could cut down what we need to do here.

Is xdebug or the profiling necessary for projects using it (such as ShellCommandBuilder) to function, or is it only used for testing/benchmarks during development? Currently xdebug is failing to compile when I try to `docker-compose up -d` on this repo, so I wonder if a temporary "flag" to disable xdebug/profiling might be helpful.


> 
> I am very happy to hear, that the ShellCommandBuilder can be of help. May I ask out of curiosity, what kind of project you are going to build with it?
> 

Sure! I haven't tried it yet, but the readme examples look like a perfect way to start securing things a bit better. The project is [servidor](https://github.com/dshoreman/servidor) - something I started 3 years ago just before Hacktoberfest to help cut down on tedious nginx configs and general server stuff.

It's using PHP's `exec()` type functions *everywhere* to do everything from creating/symlinking nginx configs, git clone/pull/etc, all the way to `user{add,mod,del}`. They're *almost guaranteed* to be dangerous, so something like ShellCommandBuilder will make it much easier to solve that :D 

> I enabled both repos with the new hacktoberfest label, your PR here should definitely be counted

Thanks!

**Comment by ChrisB9** [comment]
Yes, they changed a lot between the versions. We currently are using in our php7 images the old version with mongodb, but i cannot install mongodb support yet in this image, because the driver itself is not finished yet:
https://github.com/mongodb/mongo-php-driver/issues/1161

You are right, that's a good idea! Xdebug and the profiler should be toggle-able while using the container. Something like 'xdebug-toggle' and 'profiler-toggle' and be off by default. I will create issues for that.

> Is xdebug or the profiling necessary for projects using it (such as ShellCommandBuilder) to function
ShellCommandBuilder only needs xdebug for infection-tests. That project requires in production no third-party library.

> Sure! I haven't tried it yet, but the readme examples look like a perfect way to start securing things a bit better. The project is servidor - something I started just before Hacktoberfest in 2018 to help cut down on tedious nginx configs and general server stuff.
That looks like a cool project! 
And it definitely sounds like ShellCommandBuilder could be a perfect helper there. We are using it in our database and file-system sync tool that creates rather complex database commands: https://github.com/phpsu/phpsu/blob/feature/43-docker-commands/src/Command/DatabaseCommand.php#L275 . Maybe that helps you as an inspiration :D 
In that project, we are actually using Symfony/Process instead of `exec()` to abstract away shell interaction.

**Comment by ChrisB9** [comment]
@dshoreman Thank you again very much for your PR and your intensive digging through xdebug code. I tested it out locally and it worked perfectly.
I updated the branch to the newest PHP8 release candidate and additionally enabled more modes, since 
All modes available here: https://github.com/xdebug/xdebug/blob/9e7440fc4cfbc70e520c66e92c38215c0cb08ce7/src/lib/lib.c

After having done that, I do agree even more with you, that it would be nice to be able to enable and disable xdebug at will.
As we would just need to switch the mode, this should be straight forward.

**Pull request merged**
